[package]
name = "debian-control"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "A parser for Debian control files"
repository = "https://github.com/jelmer/debian-control-rs"
homepage = "https://github.com/jelmer/debian-control-rs"

[dependencies]
regex = "1"
rowan = "0.15.11"
