[package]
name = "deb822"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A parser for deb822 files"

[dependencies]
regex = "1"
