[package]
name = "deb822-lossless"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
version = { workspace = true }
edition = "2021"
license = "Apache-2.0"
description = "A parser for Debian control files"
repository = "https://github.com/jelmer/deb822-lossless"
homepage = "https://github.com/jelmer/deb822-lossless"

[workspace]
members = ["debian-control", "debian-copyright"]

[workspace.package]
version = "0.1.4"

[dependencies]
debversion = "0.2.2"
regex = "1"
rowan = "0.15.11"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]
