[package]
name = "debian-control"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
version = { workspace = true }
edition = "2021"
license = "Apache-2.0"
description = "A parser for Debian copyright files"
repository = "https://github.com/jelmer/deb822-lossless"
homepage = "https://github.com/jelmer/deb822-lossless"

[dependencies]
rowan = "0.15.11"
debversion = "0.2.2"
regex = "1"
deb822-lossless = { version = "0.1.4", path = ".." }
