[package]
name = "debian-control"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
version = { workspace = true }
edition = "2021"
license = "Apache-2.0"
description = "A parser for Debian control files"
repository = "https://github.com/jelmer/debian-control-rs"
homepage = "https://github.com/jelmer/debian-control-rs"

[dependencies]
rowan = "0.15.11"
debversion = "0.2.2"
regex = "1"
deb822-lossless = { path = ".."  }
