[package]
name = "debian-copyright"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
version = { workspace = true }
edition = "2021"
license = "Apache-2.0"
description = "A parser for Debian copyright files"
repository = "https://github.com/jelmer/debian-copyright"
homepage = "https://github.com/jelmer/debian-copyright"

[dependencies]
debversion = "0.2.2"
deb822-lossless = { path = ".." }
regex = "1.10.2"
